version: '3.1'

services:
  dbserver:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: konferenz-management

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  express-server:
    build: ./server
    restart: always
    ports:
      - 3000:3000
      - 3443:3443
    depends_on:
      - dbserver
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  frontend:
    build: .
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl.conf:/usr/local/apache2/conf/ssl.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro


