version: "3.1"

services:
  dbserver:
    container_name: conference-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - conference-management

  express-server:
    container_name: conference-api
    build: ./server
    restart: always
    depends_on:
      - dbserver
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL}
#      - FRONTEND_PORT=${FRONTEND_PORT}
      - EXPRESS_PORT_HTTP=${EXPRESS_PORT_HTTP}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DB_TYPE="mariadb"
      - DB_HOST="dbserver"
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER="root"
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_PORT="3306"
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - ISSUER=${ISSUER}
      - CALLBACK_URL=${CALLBACK_URL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SENDER_MAIL=${SENDER_MAIL}
    ports:
      - 11000:11000
    networks:
      - conference-management

  frontend:
    container_name: conference-frontend
    build:
      context: .
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_BACKEND_PROTOCOL=${VITE_BACKEND_PROTOCOL}
    restart: always
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_BACKEND_PROTOCOL=${VITE_BACKEND_PROTOCOL}
    ports:
      - 11001:11001
    networks:
      - conference-management

networks:
  conference-management:
    driver: bridge
