version: "3.1"

services:
  dbserver:
    container_name: conference-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - conference-management

  express-server:
    container_name: conference-api
    build: ./server
    restart: always
    depends_on:
      - dbserver
    environment:
      - EXPRESS_IP=${EXPRESS_IP}
      - FRONTEND_URL=${FRONTEND_URL}
      - FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - EXPRESS_PORT_HTTP=${EXPRESS_PORT_HTTP}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - FRONTEND_IP=${FRONTEND_IP}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - ISSUER=${ISSUER}
      - AUTHORIZATION_URL=${AUTHORIZATION_URL}
      - TOKEN_URL=${TOKEN_URL}
      - USERINFO_URL=${USERINFO_URL}
      - CALLBACK_URL=${CALLBACK_URL}
      - INTROSPECT_URL=${INTROSPECT_URL}
      - ENDSESSION_ENDPOINT=${ENDSESSION_ENDPOINT}
      - KEYCLOAK_PUBLIC_KEY=${KEYCLOAK_PUBLIC_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SENDER_MAIL=${SENDER_MAIL}
    ports:
      - 11000:11000
    networks:
      - conference-management

  frontend:
    container_name: conference-frontend
    build:
      context: .
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_BACKEND_PROTOCOL=${VITE_BACKEND_PROTOCOL}
    restart: always
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_BACKEND_PROTOCOL=${VITE_BACKEND_PROTOCOL}
    ports:
      - 11001:11001
    networks:
      - conference-management

networks:
  conference-management:
    driver: bridge
