version: "3.1"

services:
  dbserver:
    container_name: conference-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    container_name: conference-phpmyadmin
    image: phpmyadmin
    restart: always
    #    expose:
    #      - 11012
    ports:
      - "127.0.0.1:11012:11012"
    environment:
      - PMA_ARBITRARY=1
      - APACHE_PORT=11012

  express-server:
    container_name: conference-api
    build: ./server
    restart: always
    depends_on:
      - dbserver
    environment:
      - EXPRESS_IP=${EXPRESS_IP}
      - FRONTEND_URL=${FRONTEND_URL}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - EXPRESS_PORT_HTTP=${EXPRESS_PORT_HTTP}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - ISSUER=${ISSUER}
      - AUTHORIZATION_URL=${AUTHORIZATION_URL}
      - TOKEN_URL=${TOKEN_URL}
      - USERINFO_URL=${USERINFO_URL}
      - CALLBACK_URL=${CALLBACK_URL}
      - INTROSPECT_URL=${INTROSPECT_URL}
      - ENDSESSION_ENDPOINT=${ENDSESSION_ENDPOINT}
    ports:
      - 3000:3000

  frontend:
    container_name: conference-frontend
    build: .
    restart: always
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - 80:80